services:
  frontend:
    image: praga16/mean-frontend:latest   # 👈 use your real Docker Hub username
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

  backend:
    image: praga16/mean-backend:latest    # 👈 use your real Docker Hub username
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URL=mongodb://mongo:27017/meanapp
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend

volumes:
  mongo_data:
